# Generated by Django 5.0.2 on 2024-02-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Звено', 'verbose_name_plural': 'Звенья'},
        ),
    ]
