# Generated by Django 5.0.2 on 2024-02-25 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, verbose_name='Электронная почта')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('release_data', models.DateField(blank=True, null=True, verbose_name='Дата выхода продукта на рынок')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('shipper', models.CharField(choices=[('F', 'Завод'), ('R', 'Розничная сеть'), ('E', 'Индивидуальный предприниматель')], verbose_name='поставщик')),
                ('arrears', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженость')),
                ('creations_date', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='providers.contacts', verbose_name='Контакты')),
                ('products', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='providers.products', verbose_name='Проукдты')),
            ],
        ),
    ]
